# Generated by Django 5.2.13 on 2026-05-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportjob',
            name='caption_mode',
            field=models.CharField(choices=[('burned', 'Burned-in'), ('srt', 'Separate .SRT')], default='burned', max_length=20),
        ),
    ]
