# Generated by Django 5.2.13 on 2026-05-01 18:53

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_exportjob_caption_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='audio_file',
            field=models.FileField(blank=True, help_text='16 kHz mono WAV extracted from the original video. Populated by populate_video_metadata(). Used by the captions app for transcription.', null=True, upload_to=videos.models.upload_audio_path),
        ),
    ]
