# Generated by Django 5.2.13 on 2026-06-01 14:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('original_text', models.TextField()),
                ('translated_text', models.TextField(blank=True, default='')),
                ('language', models.CharField(default='en', max_length=10)),
                ('font_family', models.CharField(default='Montserrat', max_length=100)),
                ('font_size', models.IntegerField(default=32)),
                ('font_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('background_color', models.CharField(default='rgba(0,0,0,0.6)', max_length=50)),
                ('bg_opacity', models.IntegerField(default=40, help_text='Controls transparency of subtitle background for ASS generation (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('position', models.CharField(choices=[('top-left', 'Top Left'), ('top-center', 'Top Center'), ('top-right', 'Top Right'), ('bottom-left', 'Bottom Left'), ('bottom-center', 'Bottom Center'), ('bottom-right', 'Bottom Right')], default='bottom-center', max_length=20)),
                ('alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10)),
                ('bold', models.BooleanField(default=False)),
                ('italic', models.BooleanField(default=False)),
                ('is_caps', models.BooleanField(default=False, help_text='Indicates if caption text should be rendered in uppercase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captions', to='videos.video')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
