# Generated by Django 6.0.4 on 2026-05-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caption',
            name='position',
            field=models.CharField(choices=[('top-left', 'Top Left'), ('top-center', 'Top Center'), ('top-right', 'Top Right'), ('bottom-left', 'Bottom Left'), ('bottom-center', 'Bottom Center'), ('bottom-right', 'Bottom Right')], default='bottom-center', max_length=20),
        ),
    ]
